import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  safelist: [
    // Ensure CSS-variable based backgrounds are generated by Tailwind
    'bg-[var(--sjmpc-green)]',
    'bg-[var(--sjmpc-gold)]',
    'bg-[var(--sjmpc-dark)]',
    'bg-[var(--sjmpc-soft)]',
    // Ensure brand tokens and gradients are always available
    'bg-brand-dark',
    'bg-brand-medium',
    'bg-brand-gold',
    'from-brand-dark',
    'via-brand-medium',
    'to-brand-dark',
  ],
  // darkMode removed
  theme: {
    extend: {
      colors: {
        'brand-yellow': '#FFD700',
        'brand-green': '#008000',
        'brand-white': '#FFFFFF',
        'brand-blue': '#0000FF',
        'brand-black': '#000000',
        brand: {
          dark: '#06452C',
          medium: '#0B5D3B',
          gold: '#D4A017',
          coral: '#E86D3B',
          soft: '#F8FAF6',
          gray: '#E5EBE6',
        },
      },
      fontFamily: {
        sans: ["var(--font-geist-sans)"],
        mono: ["var(--font-geist-mono)"],
      },
      screens: {
        'xs': '420px',
        '3xl': '1600px',
      },
      spacing: {
        '18': '4.5rem',
        '88': '22rem',
      },
      animation: {
        'fade-in': 'fadeIn 0.5s ease-in-out',
        'slide-in': 'slideIn 0.3s ease-out',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideIn: {
          '0%': { transform: 'translateX(-100%)' },
          '100%': { transform: 'translateX(0)' },
        },
      },
      boxShadow: {
        '3xl': '0 35px 60px -12px rgba(0, 0, 0, 0.25)',
      },
    },
  },
  plugins: [],
};

export default config;