-- AlterTable
ALTER TABLE "PMESSession" ADD COLUMN "zoomJoinUrl" TEXT;
ALTER TABLE "PMESSession" ADD COLUMN "zoomMeetingId" TEXT;
ALTER TABLE "PMESSession" ADD COLUMN "zoomPassword" TEXT;
ALTER TABLE "PMESSession" ADD COLUMN "zoomStartUrl" TEXT;

-- CreateTable
CREATE TABLE "LoanApplication" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "name" TEXT NOT NULL,
    "pbNo" TEXT NOT NULL,
    "contactNo" TEXT NOT NULL,
    "address" TEXT NOT NULL,
    "loanType" TEXT NOT NULL,
    "idType" TEXT NOT NULL,
    "idFile" TEXT,
    "loanAmount" REAL NOT NULL,
    "term" INTEGER NOT NULL,
    "purpose" TEXT NOT NULL,
    "promissoryNoteAmount" REAL,
    "promissoryNoteTerm" TEXT,
    "promissoryNotePaymentSchedule" TEXT,
    "promissoryNoteStartingOn" TEXT,
    "makerName1" TEXT,
    "makerName2" TEXT,
    "coMakerName1" TEXT,
    "coMakerName2" TEXT,
    "witnessName1" TEXT,
    "witnessName2" TEXT,
    "assignmentAmount" REAL,
    "regularSavings" TEXT,
    "ultimaSavings" TEXT,
    "alkansyaSavings" TEXT,
    "timeDeposit" TEXT,
    "otherDeposits" TEXT,
    "assignmentPbNo" TEXT,
    "shareCapital" TEXT,
    "signatureDate" TEXT,
    "assignmentMaker1" TEXT,
    "assignmentMaker2" TEXT,
    "assignmentCoMaker1" TEXT,
    "assignmentCoMaker2" TEXT,
    "assignmentWitness1" TEXT,
    "assignmentWitness2" TEXT,
    "makerSpouseName" TEXT,
    "assignmentCoMakerName1" TEXT,
    "assignmentCoMakerName2" TEXT,
    "assignmentWitnessName1" TEXT,
    "assignmentWitnessName2" TEXT,
    "memberIncome" REAL,
    "spouseIncome" REAL,
    "otherIncome" REAL,
    "businessIncome" REAL,
    "foodExpense" REAL,
    "clothingExpense" REAL,
    "shelterExpense" REAL,
    "educationExpense" REAL,
    "electricWaterExpense" REAL,
    "helperExpense" REAL,
    "loanRepaymentExpense" REAL,
    "miscellaneousExpense" REAL,
    "netIncome" REAL,
    "committeeApproved" REAL,
    "committeeReduced" REAL,
    "receivedBy" TEXT,
    "checkedBy" TEXT,
    "approvedBy" TEXT,
    "referenceNo" TEXT,
    "loanTypeDisclosure" TEXT,
    "loanAmountDisclosure" REAL,
    "charges" REAL,
    "netProceeds" REAL,
    "effectiveInterestRate" REAL,
    "nominalInterestRate" REAL,
    "penalty" REAL,
    "interestRate" REAL,
    "voucherNo" TEXT,
    "mop" TEXT,
    "processor" TEXT,
    "status" TEXT NOT NULL DEFAULT 'pending',
    "reviewedBy" TEXT,
    "reviewedAt" DATETIME,
    "notes" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL
);
